#ifndef SINGLE_ARM_CONFIG_H
#define SINGLE_ARM_CONFIG_H

#include <stdint.h>

#define SINGLE_ARM_JOINT_COUNT 6U

#define ENABLE_SERVO_CENTERING_COMMAND 0U
#define ENABLE_BOOT_ID1_AUTOCONFIG 0U

#define HOST_BINARY_FIRMWARE_VERSION UINT32_C(0x00020700)
#define HOST_BINARY_CAPABILITIES UINT32_C(0x0000000F)
#define HOST_BINARY_HEARTBEAT_TIMEOUT_MS UINT32_C(500)

/*
 * STS3215 동작 중 보호 기준.
 * load 1000은 최대 출력 100%, current 1은 약 6.5mA다.
 * 100ms 간격으로 2회 연속 초과할 때 동작을 중단한다.
 */
#define SERVO_MOTION_SAFETY_SAMPLE_MS UINT32_C(100)
#define SERVO_MOTION_LOAD_LIMIT_RAW UINT16_C(800)
#define SERVO_MOTION_CURRENT_LIMIT_RAW UINT16_C(320)
#define SERVO_MOTION_LIMIT_CONSECUTIVE UINT8_C(2)

#endif /* SINGLE_ARM_CONFIG_H */
