#ifndef SINGLE_ARM_CONFIG_H
#define SINGLE_ARM_CONFIG_H

#include <stdint.h>

#define SINGLE_ARM_JOINT_COUNT 6U

#define ENABLE_SERVO_CENTERING_COMMAND 0U
#define ENABLE_BOOT_ID1_AUTOCONFIG 0U

#define HOST_BINARY_FIRMWARE_VERSION UINT32_C(0x00020500)
#define HOST_BINARY_CAPABILITIES UINT32_C(0x00000007)
#define HOST_BINARY_HEARTBEAT_TIMEOUT_MS UINT32_C(500)

#endif /* SINGLE_ARM_CONFIG_H */
